site_name: Farming Fortune Guide
repo_name: Fortune Guide
edit_uri: edit/main/docs/
repo_url: https://github.com/superhize/Guide
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - search.share
    - navigation.indexes
    - content.action.edit

markdown_extensions:
  - def_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - toc:
      slugify:
        !!python/object/apply:pymdownx.slugs.slugify { kwds: { case: lower } }
      permalink: true
  - admonition
  - pymdownx.smartsymbols
  - pymdownx.betterem
  - attr_list
  - tables
  - abbr
  - footnotes
  - md_in_html
  - pymdownx.highlight
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar
  - pymdownx.arithmatex:
      generic: true
      block_tag: "pre"
  - pymdownx.mark
  - pymdownx.striphtml:
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.saneheaders
nav:
  - "Fortune Guide":
    - "Main": index.md
    - "Skills Level": skills.md
    - "Extra Farming Fortune Perk": extra_farming_fortune_perk.md
    - "Garden Farming Fortune Account Upgrade": garden_fortune_account_upgrade.md
    - "Crop Upgrade": crop_upgrade.md
    - "Garden Plot": garden_plot.md
    - "Tools": tools.md
    - "Armors": armors.md
    - "Pets": pets.md
    - "Pets Item": pet_item.md
    - "Accessories": accessories.md
    - "Personal Best": personal_best.md
    - "Misc": misc.md
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date-localized:
      enable_creation_date: true
extra:
  version:
    provider: mike